// Generated by CoffeeScript 1.6.2
(function() {
  var MabogoGraph,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  MabogoGraph = (function() {
    function MabogoGraph(body, data) {
      this.body = body;
      this._updateGraph = __bind(this._updateGraph, this);
      this.vis = this.body.find("svg#mobogo-graph");
      this.svg = d3.select(this.vis[0]);
      this._setup();
      this._setupData(data);
      this._drawChart();
    }

    MabogoGraph.prototype._setup = function() {
      this.graphWidth = 800;
      this.graphHeight = 600;
      this.colorScale = d3.scale.category20();
      return this.force = d3.layout.force().size([this.graphWidth, this.graphHeight]).linkDistance(110).charge(-500);
    };

    MabogoGraph.prototype._setupData = function(data) {
      var circleRadius, countExtent, nodesMap;

      countExtent = d3.extent(data.nodes, function(d) {
        return d.links;
      });
      circleRadius = d3.scale.sqrt().range([6, 16]).domain(countExtent);
      data.nodes.forEach(function(node) {
        return node.radius = circleRadius(node.links);
      });
      nodesMap = this._mapNodes(data.nodes);
      data.links.forEach(function(link) {
        link.source = nodesMap.get(link.source);
        return link.target = nodesMap.get(link.target);
      });
      return this.force.nodes(data.nodes).links(data.links).on("tick", this._updateGraph).start();
    };

    MabogoGraph.prototype._mapNodes = function(nodes) {
      var nodesMap;

      nodesMap = d3.map();
      nodes.forEach(function(node) {
        return nodesMap.set(node.id, node);
      });
      return nodesMap;
    };

    MabogoGraph.prototype._drawChart = function() {
      this.svg.attr('width', this.graphWidth).attr("height", this.graphHeight);
      this._addMarkers();
      this._addPaths();
      this._addNodes();
      return this._addText();
    };

    MabogoGraph.prototype._addMarkers = function() {
      return this.svg.append("svg:defs").selectAll("marker").data(["friend", "acquaintance"]).enter().append("svg:marker").attr("id", String).attr("viewBox", "0 -5 10 10").attr("refX", 15).attr("refY", -1.5).attr("markerWidth", 10).attr("markerHeight", 10).attr("orient", "auto").append("svg:path").attr("d", "M0,-5L10,0L0,5");
    };

    MabogoGraph.prototype._addPaths = function() {
      return this.path = this.svg.append("svg:g").selectAll("path").data(this.force.links()).enter().append("svg:path").attr("class", function(d) {
        return "link " + d.type;
      }).attr("marker-end", function(d) {
        return "url(#" + d.type + ")";
      });
    };

    MabogoGraph.prototype._addNodes = function() {
      var _this = this;

      return this.node = this.svg.append("svg:g").selectAll("circle").data(this.force.nodes()).enter().append("svg:circle").attr("r", function(d) {
        return d.radius;
      }).style("fill", function(d) {
        return _this.colorScale(d.type);
      }).call(this.force.drag);
    };

    MabogoGraph.prototype._addText = function() {
      this.text = this.svg.append("svg:g").selectAll("g").data(this.force.nodes()).enter().append("svg:g");
      this.text.append("svg:text").attr("x", 8).attr("y", ".31em").attr("class", "shadow").text(function(d) {
        return d.name;
      });
      return this.text.append("svg:text").attr("x", 8).attr("y", ".31em").text(function(d) {
        return d.name;
      });
    };

    MabogoGraph.prototype._updateGraph = function() {
      this.path.attr("d", function(d) {
        var _this = this;

        return (function(dx, dy) {
          var dr;

          dr = Math.sqrt(dx * dx + dy * dy);
          return "M" + d.source.x + "," + d.source.y + "A" + dr + "," + dr + " 0 0,1 " + d.target.x + "," + d.target.y;
        })(d.target.x - d.source.x, d.target.y - d.source.y);
      });
      this.node.attr("transform", function(d) {
        return "translate(" + d.x + "," + d.y + ")";
      });
      return this.text.attr("transform", function(d) {
        return "translate(" + d.x + "," + d.y + ")";
      });
    };

    return MabogoGraph;

  })();

  $(function() {
    return $("#mobogo-graph-container").each(function() {
      var _this = this;

      return d3.json("data.json", function(err, data) {
        return new MabogoGraph($(_this), data);
      });
    });
  });

}).call(this);
